FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
COPY kafka_consumer/ ./kafka_consumer/
COPY config/ ./config/

RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "kafka_consumer/consumer.py"]
