FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
COPY kafka_producer/ ./kafka_producer/
COPY config/ ./config/

RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "kafka_producer/producer.py"]
