global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Configuración para recopilar métricas del propio Prometheus
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Configuración para recopilar métricas del servicio simulado
  - job_name: 'metrics-simulator'
    static_configs:
      - targets: ['metrics-simulator:8000']
    scrape_interval: 5s
    metrics_path: '/metrics'